-- Database: GLOBALPLA Metadata version: 2 Exported: Oct 8, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_6011_PL_MAINT" (
 "PRODUCT_LINE" CHAR(2) NOT NULL,
 "PRODUCT_LINE_DESC" CHAR(10),
 "PRODUCT_LINE_NAME" CHAR(30) );
-- End Multi-Line Statement
ALTER TABLE "GCG_6011_PL_MAINT" ADD CONSTRAINT "PK_PRODUCT_LINE" PRIMARY KEY  ( "PRODUCT_LINE" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
