Create Table "GCG_6011_Commissions"(
"CUSTOMER" CHAR(6), 
"SALESPERSON" CHAR(3), 
"INVOICE" CHAR(7), 
"DATE_INVOICE" DATE,
"ORDER_NO" CHAR(7), 
"ORDER_SUFFIX" CHAR(4), 
"ORDER_LINE" CHAR(4),
"COMM_RATE" DOUBLE,
"COMMISSION" DOUBLE,
"NOTE" LONGVARCHAR,
"COMM_MOD" CHAR(1) DEFAULT 'N',
"COMM_PAID" BIT);

CREATE INDEX "GCG_6011_Commissions" ON "GCG_6011_Commissions"("CUSTOMER", "SALESPERSON", "INVOICE", "ORDER_NO", "ORDER_SUFFIX", "ORDER_LINE");