CREATE TABLE "GCG_6011_GRIDVIEW" (
 "CUST_VIEW_NAME" VARCHAR(100),
 "USER_ID" CHAR(20),
 "SERIALIZE_TEXT" LONGVARCHAR,
 "NAVIGATION" VARCHAR(100),
 "STANDARD" BIT NOT NULL );

CREATE INDEX "GCG_6011_GRIDVIEW" USING 0 IN DICTIONARY  ON "GCG_6011_GRIDVIEW" ( "CUST_VIEW_NAME" , "NAVIGATION" );